spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

haemi:
  openapi:
    include-local-server: false
  jwt:
    secret: ${JWT_SECRET}
  security:
    elder-health-encryption-key: ${ELDER_HEALTH_ENCRYPTION_KEY}
